Update patcher-minimal
Adding some more stuff to get a correct output image

diff --git a/patcher-minimal b/patcher-minimal
--- a/patcher-minimal
+++ b/patcher-minimal
@@ -84,22 +84,22 @@ echo "successfully finished patch to fragmented image!"
 # reassemble fragmented image
 mkdir $csd/output
 echo "attempting to defragment image! if your image is corrupted, this may not end well..."
-$csd/magiskboot repack $csd/header.img $csd/output/output.img
-existance $csd/output/output.img "echo assembled output.img! && cd $csd" "echo output.img not found, exiting && exit 1"
+$csd/magiskboot repack $csd/header.img $csd/output/recovery.img
+existance $csd/output/recovery.img "echo assembled recovery.img! && cd $csd" "echo recovery.img not found, exiting && exit 1"
 
 # sign patched image with keyfile
 echo "extracting public key to phh.pub.bin..."
 python3 $csd/avbtool extract_public_key --key $csd/keys/phh.pem --output $csd/keys/phh.pub.bin &&
 echo "signing patched image with key..."
-python3 $csd/avbtool add_hash_footer --image $csd/output/output.img --partition_name recovery --partition_size $(wc -c $csd/raw.img | cut -f 1 -d ' ') --key $csd/keys/phh.pem --algorithm SHA256_RSA4096
+python3 $csd/avbtool add_hash_footer --image $csd/output/recovery.img --partition_name recovery --partition_size $(wc -c $csd/raw.img | cut -f 1 -d ' ') --key $csd/keys/phh.pem --algorithm SHA256_RSA4096
 echo "signed image successfully!"
 
 # package image for use in odin
 echo "packaging image for odin..."
-tar -cvf $csd/output/output.tar $csd/output/output.img &&
-md5sum -t $csd/output/output.tar >> $csd/output/output.tar &&
-mv $csd/output/output.tar $csd/output/output.tar.md5 &&
-echo "successfully packaged output.img -> output.tar.md5"
+tar -cvf $csd/output/patched-recovery.tar $csd/output/recovery.img &&
+md5sum -t $csd/output/patched-recovery.tar >> $csd/output/patched-recovery.tar &&
+mv $csd/output/patched-recovery.tar $csd/output/patched-recovery.tar.md5 &&
+echo "successfully packaged recovery.img -> patched-recovery.tar.md5"
 
 # hehe
 echo "enjoy! hope what you're trying to do works."
